### ISSUE TITLE
Scim client - test source resources references UMA1 instead of uma2 discovery

### ISSUE THREAD

**Issue by mtgluu** [GluuFederation/SCIM-Client#68]
https://github.com/GluuFederation/SCIM-Client/blob/6f114447c3a6f3636b272dfded0b91fd8cfd7e85/src/test/resources/testng.properties#L9 

This line should read:
"umaMetaDataUrl=${test.server.name}/.well-known/uma2-configuration"

**Comment by jgomer2001** [comment]
This property can be removed or ignored. The [factory method](https://github.com/GluuFederation/SCIM-Client/blob/version_3.1.2/src/main/java/gluu/scim2/client/factory/ScimClientFactory.java#L14) for UMA is not actually using it since the metadata is obtained by means of the `as_uri` header value. [For instance see here](
https://github.com/GluuFederation/SCIM-Client/blob/version_3.1.2/src/main/java/gluu/scim2/client/UmaScimClient.java#L147).
