### ISSUE TITLE
UMA SCIM Client should use one HTTP client library 

### ISSUE THREAD

**Issue by yurem** [GluuFederation/SCIM-Client#9]
Currently in SCIM Client we uses 2 network frameworks:
1) commons-httpclient
2) resteasy-jaxrs

For one we uses for SCIM API calls. And second one we uses for oxAUth UMA calls.
This introduce some libraries duplicity and can led to network connections overload because both  frameworks may create pools.
I offer to switch to resteasy-jaxrs only. It's oriented to simplify REST API client development. We uses it in oxAuth client library. Also in this case both SCIM and UMA client should use one executor. Hence it will simplify SCIM client library.

**Comment by willow9886** [comment]
@shekhar16 / @yurem has this been resolved?

**Comment by jirisedlak** [comment]
+1 for this.

In our environment, I have to use custom executor in order to connect to gluu server successfully. The issue is with UmaClient. Currently, there is no way to pass the custom executor to UmaClient. Here are the changes I have made to in my forked clients:

https://github.com/jirisedlak/SCIM-Client/commit/91aab30205c503889328030e5ce8cc38ebd66a81
https://github.com/jirisedlak/oxAuth/commit/079814b1531477c79155901ed693c13d6b4685ee

Would it be possible to include these changes in your code base?

**Comment by worm333** [comment]
Created this [pull request](https://github.com/GluuFederation/SCIM-Client/pull/20)
